"""expand branches for chi nhanh screen

Revision ID: 03985722c08d
Revises: 2ef2e30204cb
Create Date: 2026-06-22 05:24:16.351255
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa



revision: str = '03985722c08d'
down_revision: str | None = '2ef2e30204cb'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


branch_status = sa.Enum('open', 'closed', 'coming_soon', name='branch_status')


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    branch_status.create(op.get_bind(), checkfirst=True)
    op.add_column('branches', sa.Column('address', sa.String(length=500), nullable=True))
    op.add_column('branches', sa.Column('image_url', sa.String(length=1000), nullable=True))
    op.add_column('branches', sa.Column('opening_time', sa.Time(), nullable=True))
    op.add_column('branches', sa.Column('closing_time', sa.Time(), nullable=True))
    op.add_column('branches', sa.Column('monthly_revenue', sa.Float(), server_default='0', nullable=False))
    op.add_column('branches', sa.Column('rating', sa.Float(), server_default='0', nullable=False))
    op.add_column('branches', sa.Column('barber_count', sa.Integer(), server_default='0', nullable=False))
    op.add_column('branches', sa.Column('seat_count', sa.Integer(), server_default='0', nullable=False))
    op.add_column('branches', sa.Column('status', branch_status, server_default='open', nullable=False))
    op.add_column('branches', sa.Column('created_by', sa.UUID(), nullable=True))
    op.add_column('branches', sa.Column('updated_by', sa.UUID(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('branches', 'updated_by')
    op.drop_column('branches', 'created_by')
    op.drop_column('branches', 'status')
    op.drop_column('branches', 'seat_count')
    op.drop_column('branches', 'barber_count')
    op.drop_column('branches', 'rating')
    op.drop_column('branches', 'monthly_revenue')
    op.drop_column('branches', 'closing_time')
    op.drop_column('branches', 'opening_time')
    op.drop_column('branches', 'image_url')
    op.drop_column('branches', 'address')
    branch_status.drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
