"""add employee_shifts table

Revision ID: 27f3b37035d4
Revises: f896a4d51529
Create Date: 2026-06-22 13:07:32.166024
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa



revision: str = '27f3b37035d4'
down_revision: str | None = 'f896a4d51529'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('employee_shifts',
    sa.Column('employee_id', sa.UUID(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('shift_type', sa.Enum('morning', 'afternoon', 'full_day', 'off', name='shift_type'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('employee_id', 'date', name='uq_employee_shift_date')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('employee_shifts')
    # ### end Alembic commands ###
