"""add deleted_at to bookings

Revision ID: 74a8087a1f09
Revises: 586ec8f40c5f
Create Date: 2026-06-22 13:39:15.467960
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa



revision: str = '74a8087a1f09'
down_revision: str | None = '586ec8f40c5f'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bookings', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bookings', 'deleted_at')
    # ### end Alembic commands ###
