"""add display_name to employees

Revision ID: a1ea2354e72b
Revises: e8c5f2a1d9b8
Create Date: 2026-06-27 08:06:18.035174
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa



revision: str = 'a1ea2354e72b'
down_revision: str | None = 'e8c5f2a1d9b8'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_activity_logs_created_at'), table_name='activity_logs')
    op.add_column('employees', sa.Column('display_name', sa.String(length=256), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('employees', 'display_name')
    op.create_index(op.f('ix_activity_logs_created_at'), 'activity_logs', ['created_at'], unique=False)
    # ### end Alembic commands ###
